<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

In [20]:
import numpy as np

## 1 User defined functions

### 1.1 Named functions that return

In [21]:

# Your code here


### 1.2 Named functions that don’t return

In [22]:

# Your code here


### 1.3 Anonymous functions

In [23]:

# Your code here


### 1.4 Optional arguments

In [24]:

# Your code here


## 2 The importance of functions?

### 2.1 An argument for functions

In [25]:

# Your code here


### 2.2 A word of caution

In [26]:

# Your code here


## Exercise 1 :  Do you know why?

In [27]:
# Your solution here
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

greeting("hi")


'Hello hi!'

If the if statement succeeds, the function will end due to the return statement within the if statement. However, if the if statement does not succeed, the function continues to the next statement, where the f-string is returned. Thus, the function still works as expected despite not having an `else` statement.

## Exercise 2 :  Calculator functions

In [28]:
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    # Check if input is a numpy array, and do zero checks based on that
    if isinstance(y, np.ndarray):
        if np.any(y == 0):
            raise Exception("No dividing by zero!")
            exit()
    else:
        if y == 0:
            raise Exception("No dividing by zero!")
            exit()
            
    return x / y



In [29]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
z=np.array([0, 27, 25, 3, 1])

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))
print(divide(x, z)) # Will produce zero division error
print(divide(10, 0)) # Will also produce zero division error

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


Exception: No dividing by zero!

## Exercise 3 :  max_info() with NumPy

In [ ]:
def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
max_info(numbers)

(83, 2)