<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

In [1]:
import numpy as np

## 1 User defined functions

### 1.1 Named functions that return

In [2]:

# Your code here
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [3]:
greeting(name="Super Man")

'Hello Super Man!'

In [4]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [5]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return

In [17]:

# Your code here
variable_test = print("hello world")
variable_test

hello world


### 1.3 Anonymous functions

In [18]:

# Your code here
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key
                                        # (i.e. the 1st element)

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [19]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [24]:
list(map(lambda x:sum(x), numbers))

[19, 20, 21, 22, 23, 24, 25, 26, 27, 28]

In [37]:
# Lambda function containing another function
# Filters the lists in numbers based on whether they contain any elements less than 3
list(filter(lambda x: all(map(lambda y: y > 2, x)), numbers))

[[6, 3, 13], [5, 4, 14], [4, 5, 15], [3, 6, 16]]

### 1.4 Optional arguments

In [30]:

# Your code here
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

## 2 The importance of functions?

### 2.1 An argument for functions

In [9]:

# Your code here


### 2.2 A word of caution

In [10]:

# Your code here


## Exercise 1 :  Do you know why?

In [11]:
# Your solution here
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

greeting("hi")


'Hello hi!'

If the if statement succeeds, the function will end due to the return statement within the if statement. However, if the if statement does not succeed, the function continues to the next statement, where the f-string is returned. Thus, the function still works as expected despite not having an `else` statement.

## Exercise 2 :  Calculator functions

In [12]:
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    # Check if input is a numpy array, and do zero checks based on that
    if isinstance(y, np.ndarray):
        if np.any(y == 0):
            raise Exception("No dividing by zero!")
            exit()
    else:
        if y == 0:
            raise Exception("No dividing by zero!")
            exit()
            
    return x / y



In [13]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
z=np.array([0, 27, 25, 3, 1])

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))
print(divide(x, z)) # Will produce zero division error
print(divide(10, 0)) # Will also produce zero division error

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


Exception: No dividing by zero!

## Exercise 3 :  max_info() with NumPy

In [ ]:
def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
max_info(numbers)