# Problem Set 1

In [6]:
# Set up
import numpy as np

## Problem 1.1

In [2]:
def v_func(z, v_0=20, a=1.25):
    return v_0 * (1 - (z / np.sqrt(a ** 2 + z ** 2)))

for val_z in [4.333, 6.5, 17.333]:
    print(v_func(val_z))

0.7836417401284268
0.35987106038705363
0.051806297873588925


## Problem 1.2

In [3]:
def quad_eqn(a, b, c):
    return (-b - np.emath.sqrt(b**2 - 4 * a * c)) / (2 * a), (-b + np.emath.sqrt(b**2 - 4 * a * c)) / (2 * a)

print(quad_eqn(6, -17, 2))


(0.12298544197833132, 2.7103478913550023)


## Problem 1.3

## Problem 1.4

In [23]:
def fall_time(height, initial_height=10, g=9.8):
    return np.sqrt((2 * (initial_height - height)) / g)

In [25]:
[fall_time(t / 4) for t in range(40, -1, -1)]

[0.0,
 0.2258769757263128,
 0.3194382824999699,
 0.3912303982179758,
 0.4517539514526256,
 0.5050762722761054,
 0.5532833351724881,
 0.5976143046671968,
 0.6388765649999398,
 0.6776309271789384,
 0.7142857142857143,
 0.7491491772643939,
 0.7824607964359516,
 0.8144110179279557,
 0.8451542547285166,
 0.8748177652797064,
 0.9035079029052512,
 0.9313146293146641,
 0.9583148474999098,
 0.9845749108635873,
 1.0101525445522108,
 1.0350983390135313,
 1.0594569267279519,
 1.083267920578793,
 1.1065666703449761,
 1.1293848786315641,
 1.1517511068997928,
 1.1736911946539272,
 1.1952286093343936,
 1.2163847404233143,
 1.2371791482634837,
 1.2576297758327863,
 1.2777531299998797,
 1.2975644374703537,
 1.3170777796132696,
 1.3363062095621219,
 1.3552618543578767,
 1.373956004405096,
 1.3923991921155663,
 1.410601261295107,
 1.4285714285714286]

## Problem 1.5

In [14]:
onearray = np.ones(16)
onezeroarray = np.zeros(16)
onezeroarray[0] = 1
onezeroarray[15] = 1
onezeroframe = np.vstack([onearray] + [onezeroarray for i in range(14)] + [onearray])
onezeroframe

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [21]:
checkerboard = np.array([[(i + j) % 2 for i in range(1, 17)] for j in range(1, 17)])
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
array3 = np.arange(1, 100, 5)

for i, no in enumerate(array3):
    if no % 3 != 0:
        array3[i] = -array3[i]

array3

array([ -1,   6, -11, -16,  21, -26, -31,  36, -41, -46,  51, -56, -61,
        66, -71, -76,  81, -86, -91,  96])