<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [20]:
import numpy as np

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [37]:
# Your code here
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [22]:

# Your code here
print(py_real_names[0])
print(py_super_names[0])

Natasha Romanoff
Black Widow


In [23]:
print(np_super_names[-1])   # Reverse indexing

Doctor Strange


### 1.3 Accessing data from a dictionary

In [38]:

# Your code here
print(superhero_info["Natasha Romanoff"])

Black Widow


### 1.4 Higher dimensional lists

In [39]:

# Your code here
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [40]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [41]:
superhero_info.items()

dict_items([('Natasha Romanoff', 'Black Widow'), ('Tony Stark', 'Iron Man'), ('Stephen Strange', 'Doctor Strange')])

## 2 Lists vs. Arrays

### 2.1 Size

In [42]:

# Your code here
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list
                                        # to create a NEW
                                        # NumPy array

In [43]:
len(py_list_2d)

10

In [44]:
len(np_array_2d)

10

In [45]:
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [46]:

# Your code here
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [47]:

# Your code here
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [48]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [53]:
list(map(lambda x: x + 10, py_list))

[11, 12, 13, 14, 15]

In [55]:
np_array + 10 # The + function is vectorised and can perform the (+10) operation across the entire array

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [56]:

# Your code here
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [58]:
py_list_1 + py_list_2 # Python's list addition, where adding lists adds the elements of the second list to the first list

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [59]:
np_array_1 + np_array_2 # Numpy Broadcasting, where the elements in the same location in both arrays are added to each other

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [60]:

# Your code here
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [61]:
np_array * 2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [62]:

# Your code here
py_list**2                      # Won't work!

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [64]:
list(map(lambda x:x**2, py_list))

[1, 4, 9, 16, 25]

In [63]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [66]:

# Your code here
np_array == 3  # Function is broadcasted across all members of the array i.e. vectorised

array([False, False,  True, False, False])

In [67]:
np_array > 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [68]:

# Your code here
sum(py_list)     # sum() is a base Python function

15

In [72]:
%%timeit
np_array.sum()

1.46 µs ± 9.68 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [74]:
%%timeit
sum(np_array) # This works since np_array can be converted to an iterable and summed over

955 ns ± 36.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Exercise 1 :  Total recall?

## Similarities between lists and arrays

- Lists and arrays both store sets of data that can be accessed via indexing.
- Lists and arrays can both be iterated over, sliced, and other array functions can generally be done on both lists and arrays.

## Differences between lists and arrays

- Arrays broadcast many operations across all their values, which lists do not do automatically. e.g `list ** 2` does not work, while `array ** 2` will broadcast the $x^2$ operation across the entire array.
- Arrays can only store one type, while lists can store many types.

## Dictionary

A dictionary is a data structure that stores data in key-value pairs. Values can be obtained by passing the key to the dictionary, upon which the dictionary returns the value associated with that key.

## Exercise 2 :  Index me

In [34]:

# Your solution here
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])                    # Prints 'a1'
print(py_list[2])                    # Prints 'c3'
print(py_list[4])                    # Prints 'e5'
print(py_list[6])                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'



a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [76]:
# Your solution here
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

for real_name, super_name in superhero_info.items():
    superhero_info[real_name] = super_name.upper()

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [36]:
# Your solution here
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]  

num_array = np.array(numbers)
np.sum(num_array == 1)



9