<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [1]:
import numpy as np

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:

# Your code here
arr_1d = np.arange(15)
print(arr_1d[0])
print(arr_1d[1:5])
print(arr_1d[1:9:2])
print(arr_1d[1:5:-1])
print(arr_1d[::-1])

0
[1 2 3 4]
[1 3 5 7]
[]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### 1.2 Subsetting by masking (Arrays only)

Note that this is only one of two examples of "advanced indexing" in numpy: the other case is when you supply an array or list of integers as an index to numpy

In [3]:

# Your code here
np_array = np.arange(10)
print(np_array[np_array > 3])
print(np_array[[True, False, True, False, True, False, True, False, True, False]])

[4 5 6 7 8 9]
[0 2 4 6 8]


In [4]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([0, 1, 2, 3])

In [5]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [6]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([0, 1, 2, 9])

In [7]:
np_array_small_3d = np.arange(8).reshape(2, 2, 2)

In [19]:
np_array_small_3d[np.array([True, False])] # Similar result to np_array_small_3d[0], but with an extra dimension

array([[[0, 1],
        [2, 3]]])

In [20]:
np_array_small_3d[np.array([[True, False], [False, True]])] # Essentially returning an array containing np_array_small_3d[0, 0, :] and np_array_small_3d[1, 1, :]

array([[0, 1],
       [6, 7]])

### 1.3 Indexing & Slicing 2D Lists

In [8]:

# Your code here
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
print(py_list_2d[1][1])
print(py_list_2d[1:5])
print(py_list_2d[1:5][1]) # First grabs the slice 1:5, then selects the second element of that slice

B
[[2, 'B'], [3, 'C'], [4, 'D'], [5, 'E']]
[3, 'C']


### 1.4 Indexing & Slicing 2D Arrays

In [9]:

# Your code here
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])
np_array_3d = np.arange(200).reshape(10, 10, 2)
print(np_array_2d[1:5])
print(np_array_2d[1:5, 1]) # Grabs all the items in the array that fit the indices

[['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']]
['B' 'C' 'D' 'E']


### Multidimensional NumPy Arrays

In [10]:
np_array_4d = np.arange(200).reshape(5, 5, -1, 2) # using -1 in reshape will select an appropriate number that can fit in the remaining dimensions
np_array_4d.shape

(5, 5, 4, 2)

In [11]:
print(np_array_4d[1, 1, 1, 1])
print(np_array_4d[:, :, :, 1]) # This returns an array with the same dimensionality as the indices i.e. a 3 dimensional array
print(np_array_4d[0:2, 0:3, 2, 0]) # This returns a 2d array
print(np_array_4d[0, ..., 0]) # ... will skip over everything that can be skipped over, treating the skipped indices as :

51
[[[  1   3   5   7]
  [  9  11  13  15]
  [ 17  19  21  23]
  [ 25  27  29  31]
  [ 33  35  37  39]]

 [[ 41  43  45  47]
  [ 49  51  53  55]
  [ 57  59  61  63]
  [ 65  67  69  71]
  [ 73  75  77  79]]

 [[ 81  83  85  87]
  [ 89  91  93  95]
  [ 97  99 101 103]
  [105 107 109 111]
  [113 115 117 119]]

 [[121 123 125 127]
  [129 131 133 135]
  [137 139 141 143]
  [145 147 149 151]
  [153 155 157 159]]

 [[161 163 165 167]
  [169 171 173 175]
  [177 179 181 183]
  [185 187 189 191]
  [193 195 197 199]]]
[[ 4 12 20]
 [44 52 60]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]


In [12]:
# Advanced indexing with multidimensional arrays
# The rules essentially work as such: The rules for advanced indexing are applied first, then the basic indexing rules are applied

# The numbers in the array provided are replaced with the results of the index np_array_4d[x, ...]
# i.e. the result of this operation is a broadcasted index operation
# i.e. 2: [np_array_4d[1, ...], np_array_4d[0, ...], np_array_4d[4, ...], np_array_4d[2, ...]
print(np_array_4d[[1, 0, 4, 2]])

# The final array depends on the shape of the initial array
print(np_array_2d[np.array([[1, 0], [0, 1]])])

# If multiple arrays are provided, they are first broadcast across each other, then the same broadcasted index operation as before happens, but as np_array_4d[x, y, z, a, ...]
# The result of the operation below is [[np_array_2d[1, 1], np_array_2d[0, 0]], [np_array_2d[0, 0], np_array_2d[0, 1]]
print(np_array_2d[np.array([[1, 0], [0, 1]]), np.array([[1, 0], [0, 1]])])

[[[[ 40  41]
   [ 42  43]
   [ 44  45]
   [ 46  47]]

  [[ 48  49]
   [ 50  51]
   [ 52  53]
   [ 54  55]]

  [[ 56  57]
   [ 58  59]
   [ 60  61]
   [ 62  63]]

  [[ 64  65]
   [ 66  67]
   [ 68  69]
   [ 70  71]]

  [[ 72  73]
   [ 74  75]
   [ 76  77]
   [ 78  79]]]


 [[[  0   1]
   [  2   3]
   [  4   5]
   [  6   7]]

  [[  8   9]
   [ 10  11]
   [ 12  13]
   [ 14  15]]

  [[ 16  17]
   [ 18  19]
   [ 20  21]
   [ 22  23]]

  [[ 24  25]
   [ 26  27]
   [ 28  29]
   [ 30  31]]

  [[ 32  33]
   [ 34  35]
   [ 36  37]
   [ 38  39]]]


 [[[160 161]
   [162 163]
   [164 165]
   [166 167]]

  [[168 169]
   [170 171]
   [172 173]
   [174 175]]

  [[176 177]
   [178 179]
   [180 181]
   [182 183]]

  [[184 185]
   [186 187]
   [188 189]
   [190 191]]

  [[192 193]
   [194 195]
   [196 197]
   [198 199]]]


 [[[ 80  81]
   [ 82  83]
   [ 84  85]
   [ 86  87]]

  [[ 88  89]
   [ 90  91]
   [ 92  93]
   [ 94  95]]

  [[ 96  97]
   [ 98  99]
   [100 101]
   [102 103]]

  [[104 105]
   [106 1

### 1.5 Growing lists

In [13]:

# Your code here
x=[1]*10
x 

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [14]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [15]:
x = [1, 2, 3, 4, 5]
x.append(6)
x

[1, 2, 3, 4, 5, 6]

## 2 Some loose ends

### 2.1 Tuples

In [23]:

# Your code here
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

1


In [24]:
# The following will NOT work
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [25]:

# Your code here
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
# The above simply assign y and z to the same object as x, which means that y and z are equivalent to x as shown below

In [26]:
y is x

True

In [27]:
z is x

True

In [29]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()
# this only creates a new object, but reuses the same data entries as the original array
# this is fine for immutable numbers, but not for mutable data values

In [30]:
y is x

False

In [31]:
z is x

False

## Exercise 1 :  Total recall?

| **Term**   | **Brief Description**                                                                                                                                                                                                                                                      |
|------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Subsetting | Subsetting is obtaining a subset list or array from a parent list or array.                                                                                                                                                                                                |
| Indexing   | Indexing is an operation that allows you to retrieve the value at a certain index of a list or numpy array.                                                                                                                                                                |
| Slicing    | Slicing is an operation that allows you to obtain a "slice" or subset of a list or numpy array.                                                                                                                                                                            |
| Masking    | Masking allows you to obtain values from a numpy array by providing another numpy array of the same size consisting of the boolean values `True` and `False`. The masking operation only returns values whose corresponding masking array index contains the value `True`. |

## Exercise 2 :  Show me the ‘odd’ letters

In [18]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers = np_array_2d[:, 0].astype('int')
odd_letters = np_array_2d[:, 1][numbers % 2 == 1]
print(odd_letters)


['A' 'C' 'E' 'G' 'I']
