<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [2]:
import numpy as np

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [ ]:

# Your code here


### 1.2 Subsetting by masking (Arrays only)

In [6]:

# Your code here
np_array = np.arange(10)
print(np_array[np_array > 3])
print(np_array[[True, False, True, False, True, False, True, False, True, False]])

[4 5 6 7 8 9]
[0 2 4 6 8]


In [7]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([0, 1, 2, 3])

In [8]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [9]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([0, 1, 2, 9])

### 1.3 Indexing & Slicing 2D Lists

In [ ]:

# Your code here


### 1.4 Indexing & Slicing 2D Arrays

In [ ]:

# Your code here


### 1.5 Growing lists

In [ ]:

# Your code here


## 2 Some loose ends

### 2.1 Tuples

In [ ]:

# Your code here


### 2.2 Be VERY careful when copying

In [ ]:

# Your code here


## Exercise 1 :  Total recall?

In [ ]:



# Your solution here




## Exercise 2 :  Show me the ‘odd’ letters

In [17]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers = np_array_2d[:, 0].astype('int')
odd_letters = np_array_2d[:, 1][numbers % 2 == 1]
print(odd_letters)


['A' 'C' 'E' 'G' 'I']
